<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>6cc58f80-34fe-45a9-8a2d-d64f8846e605</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Puya.Net\Puya.Net.csproj" />
    <ProjectReference Include="..\Puya.Samples\Puya.Samples.csproj" />
  </ItemGroup>

</Project>
